// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZcxKPyGfRFvBLwIxgx0fUf3fhPcWyqc',
    appId: '1:798232547175:web:f75d9da4587e0a339f29c2',
    messagingSenderId: '798232547175',
    projectId: 'racetracker-e0e90',
    authDomain: 'racetracker-e0e90.firebaseapp.com',
    storageBucket: 'racetracker-e0e90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj8mrgmK5XaQLNOXNSBn7b7nIKXbEcdOw',
    appId: '1:798232547175:android:7e4f512fda71ec3c9f29c2',
    messagingSenderId: '798232547175',
    projectId: 'racetracker-e0e90',
    storageBucket: 'racetracker-e0e90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7gi3uu61g-tpcfqPjCM99WY5NfGMg-3s',
    appId: '1:798232547175:ios:562ee391c75b6af19f29c2',
    messagingSenderId: '798232547175',
    projectId: 'racetracker-e0e90',
    storageBucket: 'racetracker-e0e90.firebasestorage.app',
    iosBundleId: 'com.example.racetrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7gi3uu61g-tpcfqPjCM99WY5NfGMg-3s',
    appId: '1:798232547175:ios:562ee391c75b6af19f29c2',
    messagingSenderId: '798232547175',
    projectId: 'racetracker-e0e90',
    storageBucket: 'racetracker-e0e90.firebasestorage.app',
    iosBundleId: 'com.example.racetrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmZcxKPyGfRFvBLwIxgx0fUf3fhPcWyqc',
    appId: '1:798232547175:web:c66ee91ba54c8b5e9f29c2',
    messagingSenderId: '798232547175',
    projectId: 'racetracker-e0e90',
    authDomain: 'racetracker-e0e90.firebaseapp.com',
    storageBucket: 'racetracker-e0e90.firebasestorage.app',
  );

}